version: '3.8'

services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../avodaco_lara/public:/var/www/html/public
    networks:
        service_net:
          ipv4_address: 172.28.4.201

  php-fpm:
    build:
      context: ../avodaco_lara
      dockerfile: ../avocado_docker/php/Dockerfile
    container_name: php-fpm
    volumes:
      - ../avodaco_lara:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    command: > 
      sh -c "chown -R www-data:www-data storage bootstrap/cache &&
        chmod -R 775 storage bootstrap/cache &&
        php-fpm"
    networks:
        service_net:
            ipv4_address: 172.28.4.3

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
        service_net:
            ipv4_address: 172.28.4.2

  frontend:
    build: 
      context: ../avocado_vue
      dockerfile: ../avocado_docker/frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
        service_net:
            ipv4_address: 172.28.4.4

volumes:
  mysql-data:

networks:
    service_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.4.0/24
